<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceptar todo</name>
   <tag></tag>
   <elementGuidId>732059fc-37c1-4473-8f53-ff7fb8cabb5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#L2AGLb > div.QS5gu.sy4vM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[3]/div[3]/span/div/div/div/div[3]/div[1]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6ec99082-cd16-425a-ae01-951790e36f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>QS5gu sy4vM</value>
      <webElementGuid>86290c8d-ccc2-4941-9b31-c2ae563b107b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ff8d48a5-4151-4160-bb9a-9282a725fd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar todo</value>
      <webElementGuid>47710569-52ff-4738-92e6-045fb647f838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L2AGLb&quot;)/div[@class=&quot;QS5gu sy4vM&quot;]</value>
      <webElementGuid>123ab148-1780-43fd-b537-88588b773da1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='L2AGLb']/div</value>
      <webElementGuid>5e1ee31f-3e82-49de-a87b-c1419b8c8e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div</value>
      <webElementGuid>85f00adf-4e8b-45df-91e2-5a1db6b0b889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Aceptar todo' or . = 'Aceptar todo')]</value>
      <webElementGuid>a13b761f-3baa-4d8d-8f9b-cf9f959414b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
