<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>3b727c1e-c3e0-4b94-b685-e65eefccc591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addNewRecordButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addNewRecordButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c789751-d48e-484b-98d7-531a8cfe646f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addNewRecordButton</value>
      <webElementGuid>e97b3eba-87e2-45b7-ad8f-162e98abbdca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c76560b1-ffd9-4f82-ae97-4834c19dbdbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>ef2180c5-a45b-4490-a1e4-e83b783dd883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>667803a5-6676-4c79-9b62-2e6386466363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addNewRecordButton&quot;)</value>
      <webElementGuid>1db1f512-4821-4528-a120-095db1a3fd9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addNewRecordButton']</value>
      <webElementGuid>3b29bf6a-5c27-44c1-ad89-0ece3f35d834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div[2]/div/button</value>
      <webElementGuid>617577e5-416f-430d-93fb-37e39877e0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>a733b495-1ee1-4a55-9ede-2c9d63e5b6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'addNewRecordButton' and @type = 'button' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>3a451af2-04bf-40e9-ba85-58de4f777dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
