<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e2bad291-5a17-4f91-94a8-92f65579df74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/ul/li[4]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>293977af-74c5-4460-8a9c-fd0a787a4224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://opencart.abstracta.us:443/image/cache/catalog/demo/macbook_2-74x74.jpg</value>
      <webElementGuid>0dc98982-c9f8-472c-be0b-af3a60388723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MacBook</value>
      <webElementGuid>62492ffe-627a-4e6e-8a7a-8ba96fb4db72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MacBook</value>
      <webElementGuid>d8a274c1-336a-4d59-835c-cbc55d39bfa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>3098899345</value>
      <webElementGuid>9786e14d-58c3-434c-b94a-597680f171d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>pagespeed.CriticalImages.checkImageForCriticality(this);</value>
      <webElementGuid>f89520fe-1843-489d-82bb-0138c0de73ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8&quot;]/ul[@class=&quot;thumbnails&quot;]/li[@class=&quot;image-additional&quot;]/a[@class=&quot;thumbnail&quot;]/img[1]</value>
      <webElementGuid>4417875d-29b2-46b0-9acb-9c12830816bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/ul/li[4]/a/img</value>
      <webElementGuid>c9604ae1-bfcc-4305-af6b-b12e6b05e836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='MacBook'])[4]</value>
      <webElementGuid>99b6bfb9-e2e0-4b9d-9c76-e4e05f46722a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/img</value>
      <webElementGuid>eec8d123-f598-4cfc-a002-b65fdc7d34b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://opencart.abstracta.us:443/image/cache/catalog/demo/macbook_2-74x74.jpg' and @title = 'MacBook' and @alt = 'MacBook']</value>
      <webElementGuid>502731b5-f14e-4c94-b976-418ecadd87c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
