<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Permanent Address_permanentAddress</name>
   <tag></tag>
   <elementGuidId>46317e20-5fb6-4f5d-84d5-2874e7cf6a4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='permanentAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#permanentAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>46a193c3-fa88-491f-9f08-8e52f3ec2f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e314b642-82dd-4248-a20a-788b3d36a667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1bd6695a-4908-4874-bf46-c013908bb1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permanentAddress</value>
      <webElementGuid>2e9af763-16c5-4fd1-a80b-e64a1b024409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2460a1f2-3404-4b89-bc4b-fd745aa8aeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permanentAddress&quot;)</value>
      <webElementGuid>cddc9a7e-4e72-4a26-b75b-825f6dc76328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='permanentAddress']</value>
      <webElementGuid>1f8362bb-95b3-41fe-8765-83e351ab3ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permanentAddress-wrapper']/div[2]/textarea</value>
      <webElementGuid>9818742c-c507-4d00-acfa-174d8886d976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/textarea</value>
      <webElementGuid>5a861586-e5f3-4475-953b-5666467ef6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'permanentAddress']</value>
      <webElementGuid>59799b7b-9a21-4465-8f71-fb463de04a46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
