<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Data_csv</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>230a0aa3-e207-4dba-aa29-ef995c607105</testSuiteGuid>
   <testCaseLink>
      <guid>b9f58c6d-3578-4365-8b6c-02576451b81a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Datos_externos/Driver_csv/Caso_drive_csv</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>16e5f805-e9c2-4bea-8478-75cf8db1bf27</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_csv/data_csv</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>16e5f805-e9c2-4bea-8478-75cf8db1bf27</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nombre</value>
         <variableId>0e11b1e8-558f-41cd-ad38-1872b4318338</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>16e5f805-e9c2-4bea-8478-75cf8db1bf27</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>apellido</value>
         <variableId>96eeffa9-222b-481b-9f76-0bde83aec400</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>16e5f805-e9c2-4bea-8478-75cf8db1bf27</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>0be68a2d-79c3-4a4a-8853-c0243b7920f7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
