<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MacBook</name>
   <tag></tag>
   <elementGuidId>54105bd4-159e-4f2d-99eb-b215bad3e817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/div/div[2]/h4/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>39cd6ef9-4f51-4a7d-a1cd-863bb03ab767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://opencart.abstracta.us:80/index.php?route=product/product&amp;product_id=43</value>
      <webElementGuid>3c0b6263-c248-4286-9647-b5c7a3577df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MacBook</value>
      <webElementGuid>e18230cd-b172-4b28-9f98-916e5e18ccdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;product-layout col-lg-3 col-md-3 col-sm-6 col-xs-12&quot;]/div[@class=&quot;product-thumb transition&quot;]/div[@class=&quot;caption&quot;]/h4[1]/a[1]</value>
      <webElementGuid>03c6d5b2-d3a8-4443-836b-6c09cfa90545</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div/div[2]/h4/a</value>
      <webElementGuid>ec8c67bd-6935-4120-8114-8674fc8aa950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MacBook')]</value>
      <webElementGuid>5af5b7dd-8883-4e01-baac-1c0dc0d6e120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://opencart.abstracta.us:80/index.php?route=product/product&amp;product_id=43'])[2]</value>
      <webElementGuid>077a86f4-08a6-4855-9eee-e9fa82216e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a</value>
      <webElementGuid>42e7e953-422f-413f-bd14-4722a8fec9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://opencart.abstracta.us:80/index.php?route=product/product&amp;product_id=43' and (text() = 'MacBook' or . = 'MacBook')]</value>
      <webElementGuid>b58a82de-d6d7-465d-9783-37402456112e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
